### ISSUE TITLE
Common.js module failing

### ISSUE THREAD

**Issue by delaneyj** [jscad/jscad-desktop#15]
On Windows 10 using dev-win

`Error: Cannot find module './nemaMount.jscad' details: Error: Cannot find module './nemaMount.jscad'`. Note both files are in the same folder.

test.jscad
```
var nema17Mount = require("./nemaMount.jscad")

debugger
function main(params) {
  return nema17Mount();
}
```

nemaMount.jscad
```
function extrudeAndMirror(profile2d, height) {
  var half = linear_extrude({ height: height }, profile2d);

  return union(half, half.mirroredX());
}

function nema17Mount() {
  var t = 3;
  var w = 50;

  var w2 = w / 2;
  var cutoutWidth = 6;
  var cutoutHeight = Math.sqrt(2 * cutoutWidth * cutoutWidth) / 2;
  var cutout = square({
    size: [cutoutWidth, cutoutWidth]
  })
    .rotateZ(45)
    .translate([w2, -cutoutHeight]);
  var cutouts = cutout.union(cutout.translate([w2, 0, 0]));
  var base = square({
    size: [w2, w]
  }).subtract(cutouts);
  var mountOffsetFromCenter = 15;

  function lowerPlate() {
    var mountHoleRadius = 4.25 / 2;
    var mountHole = circle({ r: mountHoleRadius }).translate([
      mountOffsetFromCenter,
      11
    ]);

    var mountHoles = hull(mountHole, mountHole.translate([0, 30]));
    var lowerPlate = base.subtract(mountHoles).translate([0, -w, 0]);

    return extrudeAndMirror(lowerPlate, t);
  }

  function upperPlate() {
    var motorMount = circle({
      r: 3.5 / 2,
      center: true
    }).translate([mountOffsetFromCenter, 5.5]);

    var motorClearance = circle({ r: 11, center: true }).translate([0, 21, 0]);

    var holes = union(
      motorMount,
      motorMount.translate([0, 31, 0]),
      motorClearance
    );
    var upperPlate = extrudeAndMirror(base.subtract(holes), t)
      .translate([0, -w, 0])
      .rotateX(-90)
      .translate([0, 0, t]);

    return upperPlate;
  }

  var bend = intersection(
    cube({ size: [w, t, t], center: [true, false, false] }),
    cylinder({ h: w, r: t, center: true })
      .rotateY(90)
      .translate([0, 0, t])
  );

  var bracket = linear_extrude(
    {
      height: t
    },
    polygon({ points: [[0, 0], [20, 0], [0, 15]] })
  )
    .rotateY(-90)
    .rotateZ(180)
    .translate([w2 - t, 0, 0]);

  var brackets = union(bracket, bracket.mirroredX());

  return union(lowerPlate(), upperPlate(), bend, brackets);
}

module.exports = nema17Mount;

```

**Comment by kaosat-dev** [comment]
hmm this is bothersome, normally the 'jscad' extension should work out of the box: could you just try changing the extension of both files to 'js' ?

**Comment by delaneyj** [comment]
No dice, required both `"./nemaMount.js"` and `"./nemaMount"`

**Comment by kaosat-dev** [comment]
wait , did you also rename `test.jscad` to `test.js`

**Comment by delaneyj** [comment]
Yes, and updated the package.json

**Comment by kaosat-dev** [comment]
I have copy & pasted your code and I am running into the same issue, I will try to find out why, sorry for the inconvenience !
There is a workaround, but it is a bit more verbose

**Comment by delaneyj** [comment]
No wories, just have a new project and thought its a great chance to learn jscad.  Nice to see the active development.

**Comment by kaosat-dev** [comment]
Thanks ! And good that you reported the issue though :) (pre pre alpha quality it is for now !) 
While I try to solve it, you can make it work like so
- add either @jscad/csg or @jscad/scad-api to your design's dependencies
- explicitly require stuff you need : 
```javascript 
const {square, circle} = require('@jscad/scad-api/').primitives2d
```
- this last bit might seem weird but you need to add module.exports = main (or any export statement) to your main file (test.js)

**Comment by kaosat-dev** [comment]
@delaneyj I would add one more thing to the above: explicitly including and 'require-ing' your dependency, is/should/will (likely) be the standard going forward: the online version of jscad relies on injecting the whole api as globals into scripts and it is quite horrendous.

**Comment by delaneyj** [comment]
Actually makes more since that way from a standard JS point of view.  Might need some details on the README for using POJO .js files.  I'm technically working now can close if you want or hold on for documentation sake for now.

**Comment by delaneyj** [comment]
It appears when doing `module.exports = main;` then `getParameterDefinitions` is never called and main's params argument is null.

**Comment by kaosat-dev** [comment]
how are you exporting ?
we have discussed this with a few other members of the community, and we have come to the conclusion, that 
`module.exports = {main, getParameterDefinitions}` **should** be the default in order not to confuse folks too much (this way , exports are always named)
currently it is kindof a weird mish mash , but next version should work with the above too , but will give you warnings and I cannot guarantee it remains a working thing :)

**Comment by delaneyj** [comment]
If I change from `module.exports = main;` to `module.exports = {main, getParameterDefinitions}` I get a new error...
```
C:\jscad-desktop\src\state.js:185 caught error TypeError: jscadScript is not a function
    at setDesignContent (C:\jscad-desktop\src\state.js:128)
    at C:\Users\DelaneyG.RWIN\Desktop\jscad-desktop\src\state.js:182
    at ScanSink.event (C:\jscad-desktop\node_modules\most\lib\combinator\accumulate.js:65)
    at MergeSink.event (C:\jscad-desktop\node_modules\most\lib\combinator\merge.js:110)
    at IndexSink.event (C:\\jscad-desktop\node_modules\most\lib\sink\IndexSink.js:28)
    at MapSink.event (C:\jscad-desktop\node_modules\most\lib\fusion\Map.js:71)
    at MergeSink.event (C:\jscad-desktop\node_modules\most\lib\combinator\merge.js:110)
    at IndexSink.event (C:\jscad-desktop\node_modules\most\lib\sink\IndexSink.js:28)
    at MulticastSource.event (C:\jscad-desktop\node_modules\@most\multicast\dist\multicast.js:82)
    at SkipRepeatsSink.event (C:\jscad-desktop\node_modules\most\lib\combinator\filter.js:80)
```

**Comment by kaosat-dev** [comment]
please update to the latest version, (git pull, npm install etc), lots of changes, that should be fixed
Just to be sure : you know this is pre - pre -pre alpha right ? :)

**Comment by delaneyj** [comment]
Latest pull works great!

Very sure its Pre-pre.  If you want me to hold off on any issues for now let me know when it goes alpha.  So usable already its hard to avoid using it!

**Comment by kaosat-dev** [comment]
No no you have been very great at finding crucial issues ! :-)  Not sure I can keep up the pace though haha
