### ISSUE TITLE
Display debug message on generation failure

### ISSUE THREAD

**Issue by aleung** [jscad/jscad-desktop#33]
The desktop just display message _'Error: Failed to generate design within an acceptable time'_ when the source code has syntax error. Most of the time, it's impossible to debug where the problem is.

At least an information about which line in file has error would be useful.

I know that it's pre-pre-alpha version. But it's an annoying issue that blocks me to use it.

**Comment by kaosat-dev** [comment]
@aleung  It was removed from the last version when the code switched to using web workers, it will be back in the next release
