### ISSUE TITLE
Error: Uncaught Error: Cannot find module

### ISSUE THREAD

**Issue by korpx** [jscad/jscad-desktop#42]
I'm getting "Error: Uncaught Error: Cannot find module 'C:UsersAndreasAppDataLocalProgramsjscad-desktop esourcesapp.asarsrccorecode-loading treeApi' line: 487, filename:module.js stack: undefined" when trying to load *.jscad files in v0.3.0.

Binary installed using jscad-desktop.Setup.0.3.0.exe

**Comment by kaosat-dev** [comment]
Hi @korpx !
can you please try going into options => disable `Experimental geometry caching` and try again ?
It is enabled by default, but will not work with Jscad scripts that do not use 100% functional api 
(in the future there will be only one API only , so this will be simpler haha)

**Comment by korpx** [comment]
Yes, your suggestion worked. Error gone.

**Comment by kaosat-dev** [comment]
Closing this , new versions default to false for the option
