### ISSUE TITLE
Add watching of all files in the dependency graph of the main module

### ISSUE THREAD

**Issue by kaosat-dev** [jscad/jscad-desktop#6]

**Comment by delaneyj** [comment]
Agreed, trying to break a complicated project into multiple files right now means completely losing Auto Reload

**Comment by kaosat-dev** [comment]
@delaneyj dealing with the tree of require() dependencies is actually relatively trivial (there are some tools using the javascript ast that return an accurate list of dependencies), and more sparse and accurate than sub dirs, so this will be in the next release :)
